[package]
name = "agriparser"
version = "1.0.0"
authors = ["Paul DE TEMMERMAN <p2trman@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.11.14"
reqwest = "0.9.18"
byteorder = "1.3.2"
roxmltree = "0.6.1"
error-chain = "0.12.1"
